sudo: required
language: python
# 2.6 for CentOS, 3.5 for OSX
python:
- '2.6'
- '3.5'
# Secure Environment Variables
env:
  secure: b1M8f4Zc2iKTTmJOKah0MQPv9Qiv/p4ExOkyzoEW04sX7uiEQ/d5sIJBCdDAFA3NlrNTAiOFf5jFj6UEHEqr8y0XzRYgQdYfi1Sy7rW0I5p8MIqbOoJExC4epEQAaWAQ0noXIR/Hgb7jr33VA5VFYiD5mkR2zCmtI9mvF9pdMpw=
# Setup the env (test dependencies)
before_install:
- ifconfig -a
- sudo /sbin/modprobe tun
- sudo apt-get update -qq
- sudo apt-get install -qq dynamips
# install the crassh & dep
install:
- pip install .
- pip install paramiko
# Get ready for the test script
before_script:
- wget -q $IOS_URL
- ls -l
- sudo dynamips -s 0:0:tap:tap0 -P 3725 -T 2001 --idle-pc=0x607081e0 -C tests/r1.txt c3725-advsecurityk9-mz.124-25c.bin &
- sleep 90
- sudo ifconfig tap0 inet 1.1.1.1 netmask 255.255.255.252
- ifconfig -a
- ping -c 4 1.1.1.2
# command to run tests (--cisco enables the dynamips tests)
script: py.test --cisco
branches:
  except:
    - docs
