sudo: required
language: python
# 2.6 for CentOS, 3.5 for OSX
python:
- '2.6'
- '3.5'
# Secure Environment Variables
env:
  secure: FicEBvDV/9nITCJW0Sh4rxadBAqJqdIUCcvjwPibPOzoGGaPO8tcjmudBg3jpCIEzlQ7X1KDtTetHpgTE62mLg67Mw600AQP248w/iVb8YiAPkQ8v/SOGyyGh7sbRb9pJIW6Gscy7HmrFKhbxWAAZop7uWg+bi/fPVfTkylgfYU=
# Setup the env
before_install:
- ifconfig -a
- sudo /sbin/modprobe tun
- sudo apt-get update -qq
- sudo apt-get install -qq dynamips
- wget -q $IOS_URL
- ls -l
- ifconfig -a
- sudo dynamips -s 0:0:tap:tap0 -P 3725 -T 2001 --idle-pc=0x607081e0 -C tests/r1.txt c3725-advsecurityk9-mz.124-25c.bin &
- sleep 90
- sudo ifconfig tap0 inet 1.1.1.1 netmask 255.255.255.252
- ifconfig -a
# install the test (crassh)
install:
- ping -c 4 1.1.1.2
- pip install .
- pip install paramiko
# command to run tests (--cisco enables the dynamips tests)
script: py.test --cisco
# Restrict to Test branch
branches:
  only:
  - tests-beta
