language: python
# 2.6 for CentOS, 3.5 for OSX
python:
  - "2.6"
  - "3.5"
# http://docs.travis-ci.com/user/multi-os/
os:
 - osx
 - linux
matrix:
  allow_failures:
    - os: osx
# Deps
install:
  - pip install .
  - pip install paramiko
# command to run tests
script: py.test
# Restrict to Test branch
branches:
  only:
      - tests-beta